version: '3'
services:
    postgres: 
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
        restart: always
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - 8080:80
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./api
        volumes: 
            - /usr/app/node_modules
            - ./api:/usr/app
        environment: # base on redis doc on dockerhub and postgres
            - REDIS_HOST=redis
            - REDIS_PORT=6379  
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /usr/app/node_modules
            - ./client:/usr/app
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /usr/app/node_modules
            - ./worker:/usr/app